apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - image: httpd
        name: kubernetes
        volumeMounts:
        - name: aniket_storage
          mountPath: /var/www/html
      volumes:
      - name: aniket_storage
        persistentVolumeClaim:
          claimName: ambastapvc
